config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  post 'todo/index' => 'todo#task_create'

  delete 'todo/index' => 'todo#task_destroy', as: 'destroy_task'

  delete 'projects/index' => 'projects#destroy', as: 'destroy_project'

  get 'task/:id/task_status' => 'todo#task_status'

  get 'todo/:task_id/up_task' => 'todo#up_task', as: 'up_task'

  get 'todo/:task_id/down_task' => 'todo#down_task', as: 'down_task'

  controller :todo do
    get 'add' => :task_new
  end

  controller :users do
    get 'registration' => :new, as: 'registration'
  end

  controller :sessions do
    get 'login' => :new
    post 'sessions/new' => :create
    delete 'logout' => :destroy
  end

  resources :projects

  resources :tasks

  root to: 'todo#index', as: 'todo'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to todo_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to todo_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label ' ' %>
    <%= f.text_field :name, :placeholder => ' Login..' %>
  </div>
  <div class="field">
    <%= f.label ' ' %>
    <%= f.text_field :email, :placeholder => ' Email..' %>
  </div>
  <div class="field">
    <%= f.label ' ' %>
    <%= f.password_field :password, :placeholder => ' Password' %>
  </div>
  <div>
    <%= f.label ' ' %>
    <%= f.password_field :password_confirmation, :placeholder => ' Confirm Password' %>
  </div>
  <div class="actions">
    <%= f.submit 'Sign Up' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<header>
  <div id='header-all'>
    <div id='login_logo'>Just ToDo App</div>
    <div class='btn_block'>
      <%= button_to 'Sign In', '/login', form_class: 'btn_header' %>
      <%= button_to 'About', login_url, form_class: 'btn_header' %>
    </div>
  </div>
</header>

<div id='reg_block'>
  <h1 id='reg_logo'>Registration</h1>

  <div id='reg_form'>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>