config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  post 'todo/index' => 'todo#task_create'

  delete 'todo/index' => 'todo#task_destroy', as: 'destroy_task'

  delete 'projects/index' => 'projects#destroy', as: 'destroy_project'

  get 'task/:id/task_status' => 'todo#task_status'

  get 'todo/:task_id/up_task' => 'todo#up_task', as: 'up_task'

  get 'todo/:task_id/down_task' => 'todo#down_task', as: 'down_task'

  controller :todo do
    get 'add' => :task_new
  end

  controller :users do
    get 'registration' => :new, as: 'registration'
  end

  controller :sessions do
    get 'login' => :new
    post 'sessions/new' => :create
    delete 'logout' => :destroy
  end

  resources :projects

  resources :tasks

  root to: 'todo#index', as: 'todo'

end

app/controllers/todo_controller.rb
class TodoController < ApplicationController

  COMPLETE_STATUS = 'complete'

  def index
    @user = User.find_by(id: session[:user_id])
  	@projects = @user.projects.order(:id)
  	@project = Project.new
    @tasks = Task.order(:id)
  end

  def new
  	@task = Task.new
  end

  def task_create
  	@project = Project.find(params[:project_id])
  	@task = @project.tasks.create(name: params[:name], status: nil )

    respond_to do |format|
      if @task.save
        format.html { redirect_to todo_path, notice: 'Task was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def task_destroy
    @task = Task.find(params[:task_id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to todo_path, notice: 'Task was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  def task_status

    @task = Task.find(params[:id])

    if @task.status == COMPLETE_STATUS
      @task.status = nil
    else
      @task.status = COMPLETE_STATUS
    end

    @task.save!
  end

  def up_task

    @task = Task.find(params[:id])
    @task.id = @task.id - 1;
    @task.save!
    respond_to do |format|
      format.html { redirect_to todo_path }
      format.js
      format.json { head :no_content }
    end

  end

end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/todo/_projects.html.erb
<% @user = User.find_by(id: session[:user_id]) %>
<% @projects = @user.projects.order(:id) %>

<% prjct = 0 %>
<% @projects.each do |project| %>

<% prjct = prjct + 1 %>

<% if project == @current_project %>
  <div class='current_project'>
<% else %>
  <div class='project'>
<% end %>

    <table class='project_title'>
      <tr>
        <th width="5%"><%= image_tag('SVG/calendar.svg') %></th>
        <th class="project_name", width="95%" style="padding-left: 18px;"><%= project.name %></th>
        <th width="5%"><%= link_to image_tag("SVG/trash.svg"), destroy_project_path(project_id: project.id), method: :delete, remote: true %>
    </table>
    <div class='task_list'>

      <% tsk = 0 %>
      <% project.tasks.each do |task| %>
        <table class='task' width="800px">
          <tr>
          <th class="task_status", width="5%">
              <% tsk = tsk + 1 %>
              <%= check_box_tag prjct.to_s+tsk.to_s, 'complete', task.status, class: 'status', data: { id: task.id } %>
            <label for=<%= prjct.to_s+tsk.to_s %>></label>
          </th>
          <th class="task_name", width="90%">
          	<%= task.name %>
          </th>
          <th class="delete_task_button"width="5%">
            <%= link_to image_tag('SVG/diff-removed.svg'), destroy_task_path(task_id: task.id), method: :delete, remote: true %>
          </th>
          </tr>
        </table>
      <% end %>
    </div>
    <div class='task_form'>
  	  <%= form_tag url_for(controller: 'todo', action: :task_create, project_id: project.id), remote: true do%>
   	    <div class='textfield'>
      	  <%= label_tag '' %>
      	  <%= text_field_tag :name, params[:name], :placeholder => ' Enter new task here..' %>
      	</div>
      	<div class='task_add_btn'>
      	  <%= submit_tag 'Add' %>
      	</div>
      <% end %>
    </div>
  </div>
<% end %>

<!-- Here is JavaScript -->

<script>
  $('.status').change(function() {
    $.get('/task/' + $(this).data('id') + '/task_status' );
  });
</script>

app/views/todo/index.html.erb
<header>
  <div id='header-all'>
    <div class='logo'>
      Your ToDo list
    </div>
    <div class='user_info'>
    <% if session[:user_id] %>
      <div id='logout_button'>
        <%= button_to 'Logout', logout_path, method: :delete %>
      </div>
    	<div id='welcome'>Hi, <%= @user.name %></div>
    <% end %>
    </div>
  </div>
</header>

<div id='projects'>
  <%= render("projects") %>
</div>
<div class='project_add'>
  <%= form_for(@project, remote: true) do |f| %>
    <%= f.text_field :name, :placeholder => ' Enter new project here..' %>
    <but><%= f.submit 'Add Project' %></but>
  <% end %>
  <%= image_tag('SVG/chevron-up.svg', :class => 'add_prjct_img') %>
</div>
<script>
  $('.project_add img').click(function() {
    $('.project_add form').toggle("blind");
  });
</script>

app/views/todo/task_create.js.erb
$('#projects').html("<%= escape_javascript render('todo/projects') %>");

app/views/todo/task_destroy.js.erb
$('#projects').html("<%= escape_javascript render('todo/projects') %>");